# Generated by Django 5.0.6 on 2024-06-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='people/%Y/%m/%d/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField()),
                ('connected_at', models.DateField()),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('where_connected', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='wish/%Y/%m/%d/')),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'Wish',
            },
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'YouTube',
            },
        ),
        migrations.CreateModel(
            name='Shaxzodbek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='shaxzodbek/%Y/%m/%d/')),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('shaxzodbek', 'Shaxzodbek'), ('wish', 'Wish'), ('people', 'People'), ('study', 'Study'), ('family', 'Family'), ('friends', 'Friends'), ('love', 'Love')], default='Shaxzodbek', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(to='repository.person')),
                ('wish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.wish')),
            ],
            options={
                'db_table': 'Shaxzodbek',
            },
        ),
    ]
