# Generated by Django 5.0.6 on 2024-06-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(upload_to='people/%Y/%m/%d/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('connected_at', models.DateField(blank=True, null=True)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('where_connected', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='wish/%Y/%m/%d/')),
                ('bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shaxzodbek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='shaxzodbek/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watches', models.BigIntegerField(default=0)),
                ('category', models.CharField(choices=[('shaxzodbek', 'Shaxzodbek'), ('wish', 'Wish'), ('people', 'People'), ('study', 'Study'), ('family', 'Family'), ('friends', 'Friends'), ('love', 'Love')], default='Shaxzodbek', max_length=15)),
                ('people', models.ManyToManyField(to='repository.people')),
                ('wish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.wish')),
            ],
        ),
    ]
