# Generated by Django 5.0.6 on 2024-06-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='bool',
            new_name='is_fulfilled',
        ),
        migrations.RemoveField(
            model_name='shaxzodbek',
            name='watches',
        ),
        migrations.AddField(
            model_name='shaxzodbek',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
