# Generated by Django 5.0.6 on 2024-06-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_rename_people_person_rename_bool_wish_is_fulfilled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'youtube',
                'verbose_name_plural': 'youtubes',
                'db_table': 'YouTube',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-connected_at'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='shaxzodbek',
            options={'ordering': ['-created_at'], 'verbose_name': 'shaxzodbek', 'verbose_name_plural': 'shaxzodbeks'},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-created_at'], 'verbose_name': 'wish', 'verbose_name_plural': 'wishes'},
        ),
        migrations.AddField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=5),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
        migrations.AlterModelTable(
            name='shaxzodbek',
            table='Shaxzodbek',
        ),
        migrations.AlterModelTable(
            name='wish',
            table='Wish',
        ),
    ]
