# Generated by Django 5.0.6 on 2024-06-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_youtube_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shaxzodbek',
            options={'verbose_name': 'shaxzodbek', 'verbose_name_plural': 'shaxzodbeks'},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'wish', 'verbose_name_plural': 'wishes'},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name': 'youtube', 'verbose_name_plural': 'youtubes'},
        ),
    ]
