# Generated by Django 5.0.6 on 2024-06-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_shaxzodbek_options_alter_wish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaxzodbek',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
