# Generated by Django 5.0.6 on 2024-06-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_alter_shaxzodbek_created_at_alter_wish_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-connected_at']},
        ),
        migrations.AlterModelOptions(
            name='shaxzodbek',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'ordering': ['-created_at']},
        ),
    ]
