# Generated by Django 5.0.6 on 2024-06-13 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_alter_person_options_alter_shaxzodbek_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
