# Generated by Django 5.0.6 on 2024-06-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_alter_person_connected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shaxzodbek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
