# Generated by Django 5.0.6 on 2024-06-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_alter_person_options_alter_shaxzodbek_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
