# Generated by Django 5.0.6 on 2024-06-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
