# Generated by Django 5.0.6 on 2024-06-13 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_alter_person_options_alter_person_connected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='connected_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shaxzodbek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 13, 22, 27, 38, 524598, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 13, 22, 28, 20, 271933, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
