# Generated by Django 5.0.6 on 2024-06-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_alter_person_connected_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person'},
        ),
    ]
