# Generated by Django 5.0.6 on 2024-06-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'Wish', 'verbose_name_plural': 'Wishes'},
        ),
    ]
