# Generated by Django 5.0.6 on 2024-06-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_alter_wish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name': 'YouTube'},
        ),
    ]
