# Generated by Django 5.0.6 on 2024-06-14 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_alter_person_birthday_alter_person_connected_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={},
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
