# Generated by Django 5.0.6 on 2024-06-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_alter_person_options_alter_wish_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shaxzodbek',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='created_at',
        ),
    ]
