# Generated by Django 5.0.6 on 2024-06-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_remove_person_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
    ]
