# Generated by Django 5.0.6 on 2024-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('who_is', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='people_images')),
            ],
            options={
                'db_table': 'People',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='wish_images')),
            ],
            options={
                'db_table': 'Wish',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='information_images')),
                ('category', models.CharField(choices=[('all', 'all'), ('aboutme', 'aboutme'), ('love.html', 'love.html'), ('friends', 'friends'), ('family', 'family'), ('projects.html', 'projects.html'), ('wish', 'wish')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ManyToManyField(to='aboutme.people')),
                ('wishes', models.ManyToManyField(blank=True, null=True, to='aboutme.wish')),
            ],
            options={
                'db_table': 'Information',
            },
        ),
    ]
