# Generated by Django 5.0.6 on 2024-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='wishes',
            field=models.ManyToManyField(blank=True, to='aboutme.wish'),
        ),
    ]
