# Generated by Django 5.0.6 on 2024-05-31 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_alter_information_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(upload_to='images/information_images'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(upload_to='images/people_images'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(upload_to='images/wish_images'),
        ),
    ]
