name: Django CI with PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: "repositoryAPI.settings"
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Migrations
        working-directory: repositoryAPI
        run: python manage.py migrate

      - name: Run Tests
        working-directory: repositoryAPI
        run: python manage.py test
      - name: Run Tests
        working-directory: repositoryAPI
        run: python manage.py test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
